<?php
require_once(__DIR__ . '/../_inc.php');
$ts->set('title', 'Internal 1');
$ts->set('main');
?>
<h1><?=$ts->get('title')?></h1>
<p>Hello there from internal 1</p>
<p>Suscipit brook park vel augue. Eros qui non dolor lakeview cemetary congue. Doming indians nisl the flats consequat ut carl b. stokes dignissim. Me cleveland museum of art john w. heisman nobis william g. mather in nibh in erat, andre norton consectetuer assum. Usus facilisis id university circle insitam amet ullamcorper jim tressel legentis nam james a. garfield parma. Ipsum processus quis lius sit insitam lorem lake erie, fiant suscipit. Consequat cum nostrud facer, blandit, quod futurum bob feller, dorothy dandridge veniam. Saepius quinta iis bernie kosar bob golic dynamicus. Geauga lake walton hills tincidunt, richmond heights. Dynamicus jesse owens typi accumsan etiam claritatem. Parma heights legunt sequitur michael stanley facer qui. University heights legentis sam sheppard aliquam eodem mark mothersbaugh typi placerat ut anne heche screamin’ jay hawkins the arcade.</p>
<p>Glenwillow me congue amet. Consuetudium investigationes moreland hills est velit don shula warrensville heights, lectores at, dolor nunc sequitur. Nunc mentor headlands shaker heights anteposuerit. Municipal stadium eodem amet autem mirum iriure litterarum paul brown. Parum decima doming qui sandy alomar eric metcalf. Gothica at east side exerci highland heights strongsville beachwood, joel grey squire’s castle qui gund arena soluta.</p>
<p>Notare harvey pekar saepius typi ea quarta sit tracy chapman. Dolore duis claritatem quis odio consequat, major everett, nisl severance hall dolor qui sit. Frank yankovic dolore lectorum hunting valley dolor praesent harlan ellison quod, vel, legere quam south euclid. Luptatum orange exerci dolore, bay village the gold coast zzril lakewood. Jim backus in jerry siegel collision bend minim aliquip decima decima quarta ad. Vero velit west side aliquam iriure michael ruhlman. Te innerbelt legunt rocky river iis eros, liber nunc diam delenit patricia heaton ipsum philip johnson. Enim parum east cleveland urban meyer nonummy dolor consectetuer esse seacula tation molly shannon peter b. lewis. Ut possim nonummy demonstraverunt dolor eleifend, pepper pike ea newburgh heights wisi. Option nihil north randall zzril bowling clari demonstraverunt eric carmen, brooklyn heights wes craven vulputate claram. Eleifend children’s museum formas hal holbrook est et lorem brecksville littera paul newman littera laoreet. Mayfield village sit oakwood cleveland.</p>
<p>The metroparks lorem george voinovich odio. Sollemnes uss cod humanitatis decima feugait magna omar vizquel john d. rockefeller. Steve harvey hendrerit browns notare nam quod broadview heights ii. Rock & roll hall of fame erat nulla valley view michael symon magna ipsum quam. Futurum ut kenny lofton elit fiant te parum per iusto qui habent anteposuerit. Vero mutationem te cavaliers bedford heights bratenahl vel dolore amet clay mathews.</p>
<?php
$ts->end('main');
echo $ts;
